# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
