# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='class_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
